fio \
    --filesize=100G \
    --runtime=30s \
    --filename="/gpfs/remote_test02/test_fio"  \
    --ioengine=libaio \
    --direct=1 \
    --time_based \
    --stonewall  \
    --iodepth=32 \
    --bs=16m \
    --rw=read \
    --name=sw16m@qd32  \
    --numjobs=64 \
    --group_reporting
