---
- hosts: h100_storage_compute
  become: yes
  become_method: sudo

  tasks:
  - name: Get kernel version
    shell: uname -r
    register: kernel_version
    changed_when: False

  # TODO(knikolla): It is possible to install the specific version of kernel-headers
  # and kernel-devel using `dnf install kernel-devel-`uname -r` kernel-headers-`uname -r`.
  # I was hoping that the below would have the same effect, but it doesn't to.
  - name: Install dependencies
    package: name={{ item }} state=present
    with_items:
    - gcc-c++
    - rpm-build
    - "kernel-devel-{{ kernel_version.stdout }}"
    - "kernel-headers-{{ kernel_version.stdout }}"

  - name: Check version of kernel
    shell: rpm -q kernel-headers
    register: kernel_headers_version
    changed_when: False

  - name: Check kernel and headers version match
    fail:
      msg: >
        The loaded kernel version doesn't match installed kernel headers.
        It may be necessary to update the kernel and kernel-headers and restart.
    when: "kernel_version.stdout not in kernel_headers_version.stdout"
    changed_when: False

  - name: Check installed version of gpfs
    shell: "rpm -qa | grep gpfs.gplbin.`uname -r`"
    register: installed_gpl
    changed_when: installed_gpl.rc == 1
    ignore_errors: True

  - name: Build GPFS Portability Layer
    shell: "/usr/lpp/mmfs/bin/mmbuildgpl --build-package"
    when: installed_gpl.changed

  - name: Find GPFS GPL RPM
    find:
      paths: /root/rpmbuild/RPMS/x86_64/
      patterns: "gpfs.gplbin-{{ kernel_version.stdout }}*"
    register: rpm_files
    when: installed_gpl.changed

  - name: Install GPFS RPM
    shell: "dnf localinstall -y /root/rpmbuild/RPMS/x86_64/gpfs.gplbin-`uname -r`*"
    when: installed_gpl.changed
