---
- hosts: h100_storage_compute

  tasks:

  - name: Configure Hosts
    become: yes
    become_method: sudo
    template:
      src: files/hosts.j2
      dest: /etc/hosts

  - name: Ensures user .ssh dir exists
    file:
      path: .ssh/
      state: directory
      mode: "700"

  - name: Ensures root .ssh dir exists
    file:
      path: /root/.ssh/
      state: directory
      owner: root
      mode: "700"
    become: yes
    become_method: sudo

#  - name: Set up passwordless sudo
#    become: yes
#    become_method: sudo
#    lineinfile:
#      path: /etc/sudoers
#      state: present
#      search_string: '%wheel'
#      line: '%wheel        ALL=(ALL)       NOPASSWD: ALL'
#      validate: 'visudo -cf %s'

  - name: Create ssh keypairs
    community.crypto.openssh_keypair:
      path: "/root/.ssh/id_rsa"
    become: yes
    become_method: sudo

  - name: Fetch ssh public keys from nodes
    fetch:
      src: /root/.ssh/id_rsa.pub
      flat: yes
      dest: "files/authorized_keys.d/{{ inventory_hostname }}.pub"
    become: yes
    become_method: sudo

  - name: Set up root authorized keys
    assemble:
      src: files/authorized_keys.d
      dest: /root/.ssh/authorized_keys
      owner: root
      mode: "600"
      remote_src: no
    become: yes
    become_method: sudo

  - name: Set up user authorized keys
    template:
      src: files/authorized_keys.d/authorized_keys
      dest: .ssh/authorized_keys
      mode: "600"

  - name: Set hostname
    become: yes
    become_method: sudo
    ansible.builtin.hostname:
      name: "{{ vars['desired_hostname'] }}"
